## numpy 기초 연습
- 출처 : 파이썬 완벽 가이드 (권철민 지음)
- Github : <https://github.com/wikibook/pymldg-rev>

### numpy 소개
1. Python 내 numpy 패키지는 **선형대수** 기반의 프로그램을 작성하기 위한 빠른 **배열연산** 속도를 보장한다. 

In [36]:
import numpy as np

입력 데이터의 차원(shape)
- 입력 데이터의 차원을 확인하는 것은 데이터 세트 간의 입출력 변환 시 필수적 요소
- 머신러닝 알고리즘 인자로 입력 시 필요한 데이터 형 변환 필요

In [47]:
array1 = np.array([1,2,3]) # ndarray (또는 numpy 배열) 로 변환하기 위한 인자를 리스트 객체로 입력 
print('array1 type :', type(array1)) 
print('array1 shape :', array1.shape) # (3,) > 1차원 배열 / Element 수 3개 (리턴값 tuple형)
print('array1 dtype :', array1.dtype) # int32
print('array1 dimension :', array1.ndim)
print('\n')

array2 = np.array([[1,2,3], 
                   [4,5,6]]) 
print('array2 type :', type(array2))
print('array2 shape :', array2.shape) # (2,3) > 2차원 배열 / Element 수 6개
print('array2 dtype :', array2.dtype)
print('array2 dimension :', array2.ndim)
print('\n')

array3 = np.array([[1,2,3]]) 
print('array3 type :', type(array3))
print('array3 shape :', array3.shape) #(1,3) > 2차원 배열 / Element 수 3개
print('array3 dtype :', array3.dtype)
print('array3 dimension :', array3.ndim)

array1 type : <class 'numpy.ndarray'>
array1 shape : (3,)
array1 dtype : int32
array1 dimension : 1


array2 type : <class 'numpy.ndarray'>
array2 shape : (2, 3)
array2 dtype : int32
array2 dimension : 2


array3 type : <class 'numpy.ndarray'>
array3 shape : (1, 3)
array3 dtype : int32
array3 dimension : 2


### ndarray 데이터 타입
- 다른 데이터 타입을 가질 수 있는 **리스트**와 달리 ndarray는 같은 데이터 타입만 가능
- 따라서, 다른 데이터형이 섞여 있는 리스트를 ndarray로 변환하면 **데이터 크기**가 큰 타입으로 형 변환을 일괄적용!

In [49]:
list1 = [1, 2, 'test']
array1 = np.array(list1)
print(array1, array1.dtype) # 숫자형값이 모두 문자열로 일괄 변환

list2 = [1, 2, 3.0]
array2 = np.array(list2)
print(array2, array2.dtype) # int형 값들이 모두 float64로 일괄 변환

['1' '2' 'test'] <U11
[1. 2. 3.] float64


### ndarray 데이터 타입변경
- ndarray 데이터의 타입 변경은 astype() 메서드를 사용
- 데이터 타입을 변경하는 것은 **대용량의 ndarray를 만들때** 메모리를 절약하기 위함
    
    예) 데이터 타입이 float형이라면 int형으로 변환하여 메모리 절약

In [50]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

[1. 2. 3.] float64


### ndarray 편리생성을 위한 메서드 : np.arange(), np.zeros(), np.ones()

In [54]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3,2)) #dtype을 정해주지 않으면 default로 float64형 데이터 생성
print(one_array)
print(one_array.dtype, one_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### ndarray 차원과 크기를 변경하는 메서드 : ndarray의 reshape()

In [58]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5)
print('array2:\n', array2)

array3 = array1.reshape(-1,2) # 2차원 ndarray로 변환 시 column 고정값에 맞는 row 개수 자동생성
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [71]:
array1 = np.arange(8) # 1차원 ndarray 생성
print('array1:\n', array1.tolist())
print('array1:\n', array1.shape)
print('-'*80)

array3d = array1.reshape((2,2,2)) #1차원 ndarray를 3차원 ndarray로 변환
print('array3d:\n', array3d.tolist())
print('array3d:\n', array3d.shape)
print('-'*80)

array4 = array3d.reshape(-1,1) # 3차원 ndarray를 2차원 ndarray로 변환
print('array4:\n', array4.tolist())
print('array4:\n', array4.shape)
print('-'*80)

array5 = array1.reshape(-1,1) # 1차원 ndarray를 2차원 ndarray로 변환
print('array5:\n', array5.tolist())
print('array5:\n', array5.shape)
print('-'*80)

array6 = array5.reshape(-1)
print('array6:\n', array6.tolist()) # 2차원 ndarray를 1차원 ndarray로 변환
print('array6:\n', array6.shape)

array1:
 [0, 1, 2, 3, 4, 5, 6, 7]
array1:
 (8,)
--------------------------------------------------------------------------------
array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array3d:
 (2, 2, 2)
--------------------------------------------------------------------------------
array4:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array4:
 (8, 1)
--------------------------------------------------------------------------------
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5:
 (8, 1)
--------------------------------------------------------------------------------
array6:
 [0, 1, 2, 3, 4, 5, 6, 7]
array6:
 (8,)
