## numpy에서 데이터 세트 선택을 위한 indexing 연습
- 출처 : 파이썬 완벽 가이드 (권철민 지음)
- Github : <https://github.com/wikibook/pymldg-rev>

### 인덱싱(indexing) 방법
1. 특정 단일 데이터만 추출 : 원하는 위치의 인덱스값을 지정
2. 슬라이싱(Slicing) : 연속된 인덱스 상의 ndarray를 추출
3. 팬시 인덱싱(Fancy Indexing) : 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정
4. 불린 인덱싱(Boolean Indexing) : 특정 조건의 True에 해당하는 인덱스 위치의 ndarray를 추출 

In [1]:
import numpy as np

### 1. 특정 단일 데이터 추출
    - axis = 0 : row 방향 / axis = 1 : column 방향

In [4]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값', array2d[0, 0])
print('(row=0, col=1) index 가리키는 값', array2d[0, 1])
print('(row=1, col=0) index 가리키는 값', array2d[1, 0])
print('(row=1, col=1) index 가리키는 값', array2d[1, 1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값 1
(row=0, col=1) index 가리키는 값 2
(row=1, col=0) index 가리키는 값 4
(row=1, col=1) index 가리키는 값 5


### 2. 슬라이싱(Slicing)
    - 슬라이싱으로 추출된 데이트는 모두 ndarray값

In [8]:
array1 = np.arange(1,10)
print(array1)

array3 = array1[1:3]
print(array3)

array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)
print(type(array6))

[1 2 3 4 5 6 7 8 9]
[2 3]
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


### 3. 팬시 인덱싱 (Fancy Indexing)

In [16]:
array1d = np.arange(1,10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

array3 = array2d[[0,1], 2]
print('array3:\n', array3)

array4 = array2d[[0,1], 0:2]
print('array4:\n', array4)

array5 = array2d[[0,1]]
print('array5:\n', array5)

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array3:
 [3 6]
array4:
 [[1 2]
 [4 5]]
array5:
 [[1 2 3]
 [4 5 6]]


### 4. 불린 인덱싱 (Boolean Indexing)
    - 필터링 조건으로 반환된 Boolean ndarray 객체에 True값이 있는 위치 인덱스값을 자동변환해서 해당 위치의 데이터만 반환 

In [20]:
array1d = np.arange(1,10)
array3 = array1d[array1d > 5]
print('(array1d > 5) 조건의 불린 인덱싱 결과 \n', array3)

print(array1d > 5)

(array1d > 5) 조건의 불린 인덱싱 결과 
 [6 7 8 9]
[False False False False False  True  True  True  True]
